[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "common"
repository.workspace = true
version.workspace    = true

[lib]
name = "common"
path = "lib.rs"

[lints]
workspace = true

[dependencies]
dioxus.workspace = true
