[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "nerd"
repository.workspace = true
version.workspace    = true

[[bin]]
name = "nerd"
path = "main.rs"

[lints]
workspace = true

[dependencies]
libs.workspace    = true
tokio.workspace   = true
topcoat.workspace = true

[build-dependencies]
topcoat = { default-features = false, features = [ "tailwind" ], version = "0.10.0" }
