name: "Release"

on:
    push:
        tags:
            - "v*"

jobs:
    tagged-release:
        name: Create GitHub Release
        permissions:
            id-token: write
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Tagged release.
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
    changelog:
        name: Update Changelog
        runs-on: ubuntu-latest
        needs: tagged-release
        steps:
            - name: Checkout repository.
              uses: actions/checkout@v5
              with:
                  ref: master
            - name: Generate changelog.
              uses: rhysd/changelog-from-release/action@v3
              with:
                  file: CHANGELOG.md
                  commit_summary_template: "chore: Update changelog."
                  args: -l 2 -c
                  footer: ""
                  github_token: ${{ secrets.GITHUB_TOKEN }}
