name: "Release"

on:
    push:
        tags:
            - "v*"

jobs:
    tagged-release:
        name: Create GitHub Release
        permissions:
            id-token: write
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Tagged release.
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false